# Generated by Django 5.2.7 on 2025-10-31 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='category_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='doerapp.servicecategory'),
        ),
    ]
