# Generated by Django 5.2.7 on 2025-10-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0002_remove_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_type',
            field=models.CharField(choices=[('immediate', 'Immediate / On-Demand'), ('scheduled', 'Scheduled / Lifestyle')], default='scheduled', max_length=20),
        ),
    ]
