# Generated by Django 5.2.7 on 2025-10-31 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0003_remove_servicecategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
    ]
