# Generated by Django 5.2.7 on 2025-11-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
