# Generated by Django 5.2.7 on 2025-11-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0008_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarposter',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Zoom/Meet/any platform URL for the live session', max_length=500),
        ),
    ]
