# Generated by Django 5.2.7 on 2025-11-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0010_alter_servicerequest_status_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='doerapp.servicerequest'),
            preserve_default=False,
        ),
    ]
