# Generated by Django 5.2.7 on 2025-11-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doerapp', '0011_review_service_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='doerapp.servicerequest'),
        ),
    ]
